 # This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
$mainMod = SUPER


env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = NIXOS_OZONE_WL,1
env = MOZ_ENABLE_WAYLAND, 1
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOW_DECORATION,1
env = GDK_SCALE,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

monitor=,preferred,auto,1
monitor=DP-1,1920x1080@180,0x0,1
exec-once = waybar
exec-once = sww_daemon

input {
    kb_layout = latam
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 0

    resize_on_border = true

}

decoration {
    rounding = 5
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
    enabled = true
    size = 3
    passes = 1
    }

}


animations {
    enabled = false
}



bind = $mainMod, Q, exec, kitty
bind = $mainMod, E, exec, dolphin
bind = $mainMod, R, exec, wofi --show drun -I -G
bind = $mainMod, B, exec, brave
bind = $mainMod, S, exec, steam

bind = $mainMod, C, killactive
bind = $mainMod, V, togglefloating
bind = $mainMod, F, fullscreen

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5


bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, M, exit
bind = $mainMod SHIFT,B, exec, killall waybar; waybar
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5
bind = , XF86AudioLowerVolume, exec, pamixer -d 5
bind = , XF86AudioMute, exec, pamixer -t


bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow



input {
    kb_layout = latam
}




